# Generated by Django 5.1.7 on 2025-11-25 03:42

import authentication.models
import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(help_text='Nombre del usuario', max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido del usuario', max_length=150, verbose_name='Apellido')),
                ('username', models.CharField(error_messages={'unique': 'Este nombre de usuario ya está en uso.'}, help_text='Nombre de usuario único', max_length=150, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, help_text='Email único para login', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('celular', models.CharField(help_text='Formato Ecuador: 09XXXXXXXX o +593XXXXXXXXX | Internacional: +código país + número', max_length=20, validators=[authentication.models.validar_celular], verbose_name='Número de celular')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Opcional: Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de nacimiento')),
                ('terminos_aceptados', models.BooleanField(default=False, help_text='Usuario acepta términos y condiciones', verbose_name='Términos y condiciones')),
                ('terminos_fecha_aceptacion', models.DateTimeField(blank=True, help_text='Fecha y hora cuando el usuario aceptó los términos', null=True, verbose_name='Fecha de aceptación de términos')),
                ('terminos_version_aceptada', models.CharField(blank=True, default='1.0', help_text='Versión de los términos y condiciones aceptados', max_length=10, null=True, verbose_name='Versión de términos aceptada')),
                ('terminos_ip_aceptacion', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se aceptaron los términos', null=True, verbose_name='IP de aceptación')),
                ('notificaciones_email', models.BooleanField(default=True, help_text='Si está desactivado, no recibirá correos de la plataforma', verbose_name='Recibir notificaciones por email')),
                ('notificaciones_marketing', models.BooleanField(default=True, help_text='Promociones, ofertas especiales y novedades', verbose_name='Recibir emails de marketing')),
                ('notificaciones_push', models.BooleanField(default=True, help_text='Notificaciones push en la aplicación móvil', verbose_name='Notificaciones push')),
                ('reset_password_code', models.CharField(blank=True, help_text='Hash del código de 6 dígitos para resetear contraseña', max_length=128, null=True, verbose_name='Código de recuperación (hasheado)')),
                ('reset_password_expire', models.DateTimeField(blank=True, db_index=True, help_text='Fecha límite para usar el código (15 minutos)', null=True, verbose_name='Expiración del código')),
                ('reset_password_attempts', models.IntegerField(default=0, help_text='Contador de intentos fallidos al verificar código de recuperación', verbose_name='Intentos de verificación del código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cuenta_desactivada', models.BooleanField(default=False, help_text='Usuario desactivó su cuenta voluntariamente', verbose_name='Cuenta desactivada')),
                ('fecha_desactivacion', models.DateTimeField(blank=True, help_text='Fecha cuando el usuario desactivó su cuenta', null=True, verbose_name='Fecha de desactivación')),
                ('razon_desactivacion', models.TextField(blank=True, help_text='Motivo por el cual el usuario desactivó su cuenta', null=True, verbose_name='Razón de desactivación')),
                ('intentos_login_fallidos', models.IntegerField(default=0, help_text='Contador de intentos fallidos de inicio de sesión', verbose_name='Intentos de login fallidos')),
                ('cuenta_bloqueada_hasta', models.DateTimeField(blank=True, help_text='Fecha hasta la cual la cuenta está temporalmente bloqueada', null=True, verbose_name='Cuenta bloqueada hasta')),
                ('ultimo_login_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP del último inicio de sesión exitoso', null=True, verbose_name='IP del último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['celular'], name='users_celular_e83223_idx'), models.Index(fields=['cuenta_desactivada'], name='users_cuenta__e71bd5_idx'), models.Index(fields=['reset_password_expire'], name='users_reset_p_430be9_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
