# Generated by Django 5.1.7 on 2025-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_activo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('repartidor', 'Repartidor'), ('admin', 'Administrador')], default='cliente', help_text='Rol actualmente seleccionado por el usuario', max_length=20, verbose_name='Rol Activo'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles_aprobados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de roles aprobados: ["cliente", "proveedor", "repartidor", "admin"]', verbose_name='Roles Aprobados'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('repartidor', 'Repartidor'), ('admin', 'Administrador')], default='cliente', help_text='Tipo principal de cuenta del usuario', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tipo_usuario'], name='users_tipo_us_785b30_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rol_activo'], name='users_rol_act_604d99_idx'),
        ),
    ]
