# Generated by Django 5.1.7 on 2025-12-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_rol_activo_user_roles_aprobados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modo_silencio',
            field=models.BooleanField(default=False, help_text='Si está activado, la app no emitirá sonidos', verbose_name='Modo silencio'),
        ),
    ]
