# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('editar_proveedor', 'Editar Proveedor'), ('editar_proveedor_contacto', 'Editar Contacto Proveedor'), ('verificar_proveedor', 'Verificar Proveedor'), ('rechazar_proveedor', 'Rechazar Proveedor'), ('activar_proveedor', 'Activar Proveedor'), ('desactivar_proveedor', 'Desactivar Proveedor'), ('editar_repartidor', 'Editar Repartidor'), ('editar_repartidor_contacto', 'Editar Contacto Repartidor'), ('verificar_repartidor', 'Verificar Repartidor'), ('rechazar_repartidor', 'Rechazar Repartidor'), ('activar_repartidor', 'Activar Repartidor'), ('desactivar_repartidor', 'Desactivar Repartidor')], db_index=True, max_length=50, verbose_name='Tipo de Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción realizada', verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la acción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', verbose_name='User Agent')),
                ('modelo_afectado', models.CharField(blank=True, help_text='Nombre del modelo afectado (Proveedor, Repartidor, User)', max_length=50, null=True, verbose_name='Modelo Afectado')),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=50, null=True, verbose_name='ID del Objeto')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Datos antes de la acción (para auditoría)', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Datos después de la acción', null=True, verbose_name='Datos Nuevos')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('administrador', models.ForeignKey(help_text='Usuario administrador que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_administrativas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Acción Administrativa',
                'verbose_name_plural': 'Acciones Administrativas',
                'db_table': 'proveedores_accion_administrativa',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['administrador', '-creado_en'], name='proveedores_adminis_beb639_idx'), models.Index(fields=['tipo_accion', '-creado_en'], name='proveedores_tipo_ac_4ba148_idx'), models.Index(fields=['modelo_afectado', 'objeto_id'], name='proveedores_modelo__fd186e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razon social', max_length=200, verbose_name='Nombre del Proveedor')),
                ('ruc', models.CharField(db_index=True, help_text='RUC o cedula del proveedor (13 digitos)', max_length=13, unique=True, verbose_name='RUC/Cedula')),
                ('ultima_modificacion_ruc', models.DateTimeField(blank=True, help_text='Fecha del ultimo cambio de RUC', null=True, verbose_name='Ultima Modificacion de RUC')),
                ('total_cambios_ruc', models.PositiveIntegerField(default=0, help_text='Contador de cambios de RUC realizados (maximo 3)', verbose_name='Total de Cambios de RUC')),
                ('telefono', models.CharField(blank=True, help_text='DEPRECADO: Se sincroniza con user.celular', max_length=17, validators=[django.core.validators.RegexValidator(message="El telefono debe tener el formato: '+593999999999'. Hasta 15 digitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, help_text='DEPRECADO: Se sincroniza con user.email', max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Direccion')),
                ('ciudad', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ciudad')),
                ('tipo_proveedor', models.CharField(choices=[('restaurante', 'Restaurante'), ('farmacia', 'Farmacia'), ('supermercado', 'Supermercado'), ('tienda', 'Tienda'), ('otro', 'Otro')], db_index=True, default='restaurante', max_length=50, verbose_name='Tipo de Proveedor')),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion del negocio', verbose_name='Descripcion')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si el proveedor esta activo en la plataforma', verbose_name='Activo')),
                ('verificado', models.BooleanField(db_index=True, default=False, help_text='Si el proveedor ha sido verificado por un administrador', verbose_name='Verificado')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de comision por pedido', max_digits=5, verbose_name='Comision (%)')),
                ('horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura')),
                ('horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='proveedores/logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Si esta lleno, el proveedor esta eliminado (soft delete)', null=True, verbose_name='Fecha de Eliminacion')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario vinculado al proveedor (creado al registrarse)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ruc'], name='proveedores_ruc_a5d69c_idx'), models.Index(fields=['activo'], name='proveedores_activo_068092_idx'), models.Index(fields=['tipo_proveedor'], name='proveedores_tipo_pr_68a632_idx'), models.Index(fields=['verificado'], name='proveedores_verific_c1a941_idx'), models.Index(fields=['user'], name='proveedores_user_id_bf93a3_idx'), models.Index(fields=['ciudad'], name='proveedores_ciudad_68ba84_idx'), models.Index(fields=['deleted_at'], name='proveedores_deleted_fd0d56_idx'), models.Index(fields=['total_cambios_ruc'], name='proveedores_total_c_f159b6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_proveedor')],
            },
        ),
    ]
