# Generated by Django 5.1.7 on 2025-11-27 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionadministrativa',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Promedio'),
        ),
        migrations.AddField(
            model_name='accionadministrativa',
            name='total_resenas',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Reseñas'),
        ),
    ]
