# Generated by Codex on 2025-12-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE rifas DROP COLUMN IF EXISTS premio;",
                "ALTER TABLE rifas DROP COLUMN IF EXISTS valor_premio;",
                "ALTER TABLE rifas DROP COLUMN IF EXISTS ganador;",
                "ALTER TABLE rifas DROP COLUMN IF EXISTS fecha_sorteo;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
