# Generated by Django 5.1.7 on 2025-12-22 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0002_remove_legacy_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', help_text='Indica si el premio está activo o ha sido cancelado', max_length=20, verbose_name='Estado del Premio'),
        ),
        migrations.AddField(
            model_name='rifa',
            name='tipo_sorteo',
            field=models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='manual', help_text='Automático (se sortea tras fecha_fin) o Manual (requiere acción de admin)', max_length=20, verbose_name='Tipo de Sorteo'),
        ),
        migrations.AddIndex(
            model_name='premio',
            index=models.Index(fields=['estado'], name='rifas_premi_estado_ca092a_idx'),
        ),
    ]
