# Generated by Django 5.1.7 on 2025-12-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0003_premio_estado_rifa_tipo_sorteo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelada')], default='activo', help_text='Indica si el premio está activo o ha sido cancelado', max_length=20, verbose_name='Estado del Premio'),
        ),
    ]
