# Generated by Django 5.1.7 on 2025-11-25 03:42

import chat.models
import django.core.validators
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('audio', 'Audio'), ('sistema', 'Mensaje del Sistema')], db_index=True, default='texto', max_length=20, verbose_name='Tipo de Mensaje')),
                ('contenido', models.TextField(blank=True, help_text='Texto del mensaje', verbose_name='Contenido del Mensaje')),
                ('archivo', models.FileField(blank=True, help_text='Imagen o audio (máx 10MB)', null=True, upload_to='chat/archivos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'mp3', 'ogg', 'm4a', 'wav']), chat.models.validar_tamano_archivo], verbose_name='Archivo Adjunto')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, verbose_name='Nombre Original del Archivo')),
                ('tamano_archivo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('duracion_audio', models.PositiveIntegerField(blank=True, help_text='Solo para mensajes de audio', null=True, verbose_name='Duración del Audio (segundos)')),
                ('leido', models.BooleanField(db_index=True, default=False, verbose_name='Mensaje Leído')),
                ('leido_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('eliminado', models.BooleanField(db_index=True, default=False, help_text='Soft delete', verbose_name='Mensaje Eliminado')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pedido_cliente', 'Chat Cliente-Repartidor (Entrega)'), ('pedido_proveedor', 'Chat Proveedor-Repartidor (Recojo)'), ('soporte', 'Chat Soporte (Proveedor-Admin)')], db_index=True, max_length=30, verbose_name='Tipo de Chat')),
                ('titulo', models.CharField(blank=True, help_text='Generado automáticamente', max_length=200, verbose_name='Título del Chat')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Chat Activo')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cerrado_en', models.DateTimeField(blank=True, help_text='Cuando se cierra/archiva el chat', null=True, verbose_name='Fecha de Cierre')),
                ('participantes', models.ManyToManyField(related_name='chats_participando', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': 'chats',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
