# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='pedido',
            field=models.ForeignKey(blank=True, help_text='Para tipos PEDIDO_CLIENTE y PEDIDO_PROVEEDOR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='chat',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Solo para tipo SOPORTE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_soporte', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.chat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(help_text='Null para mensajes del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['tipo', 'activo'], name='chats_tipo_4f39a2_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['pedido'], name='chats_pedido__854b70_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['proveedor'], name='chats_proveed_98d449_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-actualizado_en'], name='chats_actuali_a1f1c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['pedido_cliente', 'pedido_proveedor']), _negated=True), ('pedido__isnull', False), _connector='OR'), name='chat_pedido_require_pedido'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'soporte'), _negated=True), ('proveedor__isnull', False), _connector='OR'), name='chat_soporte_require_proveedor'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['chat', 'creado_en'], name='mensajes_chat_id_bf6913_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['chat', 'leido', 'eliminado'], name='mensajes_chat_id_28d905_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente'], name='mensajes_remiten_23cab3_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['tipo'], name='mensajes_tipo_4ade32_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['-creado_en'], name='mensajes_creado__a3b09d_idx'),
        ),
    ]
