# Generated by Django 5.1.7 on 2025-12-14 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_mensaje_remitente'),
        ('pedidos', '0007_remove_pedido_pedido_grupo'),
        ('proveedores', '0002_accionadministrativa_calificacion_promedio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'pedido_proveedor'), _negated=True), ('proveedor__isnull', False), _connector='OR'), name='chat_pedido_proveedor_require_proveedor'),
        ),
    ]
