# analysis_options.yaml - Configuración optimizada para desarrollo
# Este archivo controla las reglas de análisis estático de Dart

include: package:flutter_lints/flutter.yaml

analyzer:
  # Excluir archivos generados automáticamente
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "build/**"
  
  # Configuración de errores
  errors:
    # Convertir algunos warnings molestos en info o ignorarlos
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    prefer_const_constructors_in_immutables: ignore
    
    # Mantener como warnings importantes
    invalid_annotation_target: warning
    missing_required_param: error
    missing_return: error
    
  # Habilitar características experimentales de Dart
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # ========================================================================
    # DESACTIVAR REGLAS QUE CAUSAN RAYAS AMARILLAS MOLESTAS
    # ========================================================================
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    prefer_const_constructors_in_immutables: false
    
    # ========================================================================
    # REGLAS DE ESTILO ACTIVADAS (Buenas prácticas sin ser molestas)
    # ========================================================================
    
    # Imports y organización
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_unnecessary_containers: true
    
    # Null safety
    avoid_null_checks_in_equality_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    
    # Async/Await
    unawaited_futures: true
    await_only_futures: true
    
    # Constructores y clases
    use_key_in_widget_constructors: true
    avoid_init_to_null: true
    
    # Naming conventions
    camel_case_types: true
    library_names: true
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    
    # Control de flujo
    avoid_print: true
    prefer_final_fields: true
    prefer_single_quotes: true
    
    # Otros
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_full_hex_values_for_flutter_colors: true
    prefer_collection_literals: true
    unnecessary_new: true
    unnecessary_const: true
    
    # ========================================================================
    # REGLAS DESACTIVADAS (Muy estrictas para desarrollo)
    # ========================================================================
    
    # Estas causan muchas advertencias innecesarias
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_constructors_first: false
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_specify_types: false
    annotate_overrides: false
    avoid_annotating_with_dynamic: false
    avoid_as: false
    avoid_catches_without_on_clauses: false
    avoid_catching_errors: false
    avoid_classes_with_only_static_members: false
    avoid_double_and_int_checks: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_field_initializers_in_const_classes: false
    avoid_implementing_value_types: false
    avoid_js_rounded_ints: false
    avoid_positional_boolean_parameters: false
    avoid_private_typedef_functions: false
    avoid_redundant_argument_values: false
    avoid_renaming_method_parameters: false
    avoid_returning_null: false
    avoid_returning_null_for_future: false
    avoid_returning_this: false
    avoid_setters_without_getters: false
    avoid_shadowing_type_parameters: false
    avoid_single_cascade_in_expression_statements: false
    avoid_slow_async_io: false
    avoid_types_on_closure_parameters: false
    avoid_unused_constructor_parameters: false
    avoid_void_async: false
    cascade_invocations: false
    directives_ordering: false
    do_not_use_environment: false
    flutter_style_todos: false
    join_return_with_assignment: false
    leading_newlines_in_multiline_strings: false
    library_prefixes: false
    missing_whitespace_between_adjacent_strings: false
    no_adjacent_strings_in_list: false
    no_runtimeType_toString: false
    omit_local_variable_types: false
    one_member_abstracts: false
    only_throw_errors: false
    package_api_docs: false
    parameter_assignments: false
    prefer_asserts_in_initializer_lists: false
    prefer_asserts_with_message: false
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_in_for_each: false
    prefer_final_locals: false
    prefer_foreach: false
    prefer_function_declarations_over_variables: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_initializing_formals: false
    prefer_inlined_adds: false
    prefer_int_literals: false
    prefer_interpolation_to_compose_strings: false
    prefer_mixin: false
    prefer_null_aware_operators: false
    prefer_relative_imports: false
    prefer_typing_uninitialized_variables: false
    provide_deprecation_message: false
    require_trailing_commas: false
    type_annotate_public_apis: false
    unnecessary_await_in_return: false
    unnecessary_brace_in_string_interps: false
    unnecessary_final: false
    unnecessary_getters_setters: false
    unnecessary_lambdas: false
    unnecessary_null_aware_assignments: false
    unnecessary_null_in_if_null_operators: false
    unnecessary_overrides: false
    unnecessary_parenthesis: false
    unnecessary_raw_strings: false
    unnecessary_statements: false
    unnecessary_string_escapes: false
    unnecessary_string_interpolations: false
    use_if_null_to_convert_nulls_to_bools: false
    use_late_for_private_fields_and_variables: false
    use_raw_strings: false
    use_setters_to_change_properties: false
    use_string_buffers: false
    use_test_throws_matchers: false
    use_to_and_as_if_applicable: false