# Generated by Django 5.1.7 on 2025-11-27 19:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_alter_itempedido_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Promedio General')),
                ('total_calificaciones', models.PositiveIntegerField(default=0, verbose_name='Total de Calificaciones Recibidas')),
                ('total_5_estrellas', models.PositiveIntegerField(default=0)),
                ('total_4_estrellas', models.PositiveIntegerField(default=0)),
                ('total_3_estrellas', models.PositiveIntegerField(default=0)),
                ('total_2_estrellas', models.PositiveIntegerField(default=0)),
                ('total_1_estrella', models.PositiveIntegerField(default=0)),
                ('promedio_puntualidad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('promedio_amabilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('promedio_calidad_producto', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_calificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Resumen de Calificaciones',
                'verbose_name_plural': 'Resúmenes de Calificaciones',
                'db_table': 'calificaciones_resumen',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente_a_repartidor', 'Cliente califica a Repartidor'), ('repartidor_a_cliente', 'Repartidor califica a Cliente'), ('cliente_a_proveedor', 'Cliente califica a Proveedor'), ('proveedor_a_repartidor', 'Proveedor califica a Repartidor'), ('repartidor_a_proveedor', 'Repartidor califica a Proveedor')], db_index=True, max_length=30, verbose_name='Tipo de Calificación')),
                ('estrellas', models.PositiveSmallIntegerField(help_text='Puntuación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Estrellas')),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional (máximo 500 caracteres)', max_length=500, null=True, verbose_name='Comentario')),
                ('puntualidad', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntualidad')),
                ('amabilidad', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Amabilidad')),
                ('calidad_producto', models.PositiveSmallIntegerField(blank=True, help_text='Solo aplica para calificaciones a proveedores', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad del Producto')),
                ('es_anonima', models.BooleanField(default=False, help_text='Si es True, el nombre del calificador no se muestra', verbose_name='Calificación Anónima')),
                ('editada', models.BooleanField(default=False, verbose_name='Fue Editada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('calificado', models.ForeignKey(help_text='Usuario que recibe la calificación', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Calificado')),
                ('calificador', models.ForeignKey(help_text='Usuario que da la calificación', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Calificador')),
                ('pedido', models.ForeignKey(help_text='Pedido asociado a esta calificación', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pedido', 'tipo'], name='calificacio_pedido__9674d5_idx'), models.Index(fields=['calificador', '-created_at'], name='calificacio_calific_2a001b_idx'), models.Index(fields=['calificado', '-created_at'], name='calificacio_calific_d58410_idx'), models.Index(fields=['tipo', '-created_at'], name='calificacio_tipo_acc828_idx'), models.Index(fields=['estrellas'], name='calificacio_estrell_4dcf76_idx')],
                'constraints': [models.UniqueConstraint(fields=('pedido', 'calificador', 'tipo'), name='unique_calificacion_por_pedido_tipo'), models.CheckConstraint(condition=models.Q(('estrellas__gte', 1), ('estrellas__lte', 5)), name='calificacion_estrellas_rango')],
            },
        ),
    ]
