# Generated by Django 5.1.7 on 2025-12-17 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('pedidos', '0009_pedido_tarifa_servicio'),
        ('productos', '0007_categoria_imagen_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('cliente_a_repartidor', 'Cliente califica a Repartidor'), ('repartidor_a_cliente', 'Repartidor califica a Cliente'), ('cliente_a_proveedor', 'Cliente califica a Proveedor'), ('cliente_a_producto', 'Cliente califica un Producto'), ('proveedor_a_repartidor', 'Proveedor califica a Repartidor'), ('repartidor_a_proveedor', 'Repartidor califica a Proveedor')], db_index=True, max_length=30, verbose_name='Tipo de Calificación'),
        ),
        migrations.CreateModel(
            name='CalificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(help_text='Valor de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Estrellas')),
                ('comentario', models.TextField(blank=True, help_text='Opinión opcional sobre el producto', max_length=500, null=True, verbose_name='Comentario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_producto', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_producto', to='pedidos.itempedido', verbose_name='Item del pedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_producto', to='pedidos.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_producto', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Calificación de Producto',
                'verbose_name_plural': 'Calificaciones de Productos',
                'db_table': 'calificaciones_producto',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'pedido', 'cliente', 'item'), name='unique_calificacion_producto_por_item')],
            },
        ),
    ]
