# Generated by Django 5.1.7 on 2025-12-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alter_calificacion_tipo_calificacionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('cliente_a_repartidor', 'Cliente califica a Repartidor'), ('repartidor_a_cliente', 'Repartidor califica a Cliente'), ('cliente_a_proveedor', 'Cliente califica a Proveedor'), ('proveedor_a_repartidor', 'Proveedor califica a Repartidor'), ('repartidor_a_proveedor', 'Repartidor califica a Proveedor')], db_index=True, max_length=30, verbose_name='Tipo de Calificación'),
        ),
        migrations.DeleteModel(
            name='CalificacionProducto',
        ),
    ]
