# Generated by Django 5.1.7 on 2025-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('terminos', 'Términos y Condiciones'), ('privacidad', 'Política de Privacidad')], max_length=20, unique=True, verbose_name='Tipo de Documento')),
                ('contenido', models.TextField(help_text='Contenido del documento legal (puede usar HTML)', verbose_name='Contenido')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este documento está actualmente vigente', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legales',
                'ordering': ['tipo'],
            },
        ),
    ]
