# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento del pedido', max_digits=8, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='cantidad × precio_unitario', max_digits=8, verbose_name='Subtotal')),
                ('notas', models.TextField(blank=True, help_text='Notas especiales del producto (ej: sin cebolla, extra queso)', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'db_table': 'pedidos_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetricasPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_pedidos', models.IntegerField(default=0)),
                ('pedidos_entregados', models.IntegerField(default=0)),
                ('pedidos_cancelados', models.IntegerField(default=0)),
                ('ingresos_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia_app', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tiempo_promedio_entrega', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Pedidos',
                'verbose_name_plural': 'Métricas de Pedidos',
                'db_table': 'pedidos_metricas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(blank=True, db_index=True, editable=False, help_text='Formato: JP-2024-000123', max_length=20, null=True, unique=True, verbose_name='Número de Pedido')),
                ('tipo', models.CharField(choices=[('proveedor', 'Pedido de Proveedor'), ('directo', 'Encargo Directo')], default='proveedor', max_length=20, verbose_name='Tipo de Pedido')),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='confirmado', max_length=20, verbose_name='Estado')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('direccion_origen', models.TextField(blank=True, null=True, verbose_name='Dirección de Origen')),
                ('latitud_origen', models.FloatField(blank=True, null=True, verbose_name='Latitud Origen')),
                ('longitud_origen', models.FloatField(blank=True, null=True, verbose_name='Longitud Origen')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('latitud_destino', models.FloatField(blank=True, null=True, verbose_name='Latitud Destino')),
                ('longitud_destino', models.FloatField(blank=True, null=True, verbose_name='Longitud Destino')),
                ('imagen_evidencia', models.ImageField(blank=True, help_text='Foto de la entrega (comprobante)', null=True, upload_to='pedidos/evidencias/%Y/%m/', verbose_name='Imagen de Evidencia')),
                ('comision_repartidor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Comisión Repartidor')),
                ('comision_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Comisión Proveedor')),
                ('ganancia_app', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ganancia App')),
                ('aceptado_por_repartidor', models.BooleanField(default=False, verbose_name='Aceptado por Repartidor')),
                ('confirmado_por_proveedor', models.BooleanField(default=False, verbose_name='Confirmado por Proveedor')),
                ('cancelado_por', models.CharField(blank=True, max_length=100, verbose_name='Cancelado Por')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('fecha_confirmado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Confirmado')),
                ('fecha_en_preparacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha En Preparación')),
                ('fecha_en_ruta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha En Ruta')),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entregado')),
                ('fecha_cancelado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cancelado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha del Cambio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó el Cambio')),
            ],
            options={
                'verbose_name': 'Historial de Pedido',
                'verbose_name_plural': 'Historial de Pedidos',
                'db_table': 'pedidos_historial',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
