# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('repartidores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que realiza el pedido', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuarios.perfil', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del pedido (null para encargos directos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, help_text='Repartidor asignado al pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='repartidores.repartidor', verbose_name='Repartidor'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', '-creado_en'], name='pedidos_estado_12eb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', '-creado_en'], name='pedidos_cliente_f7cab8_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['proveedor', '-creado_en'], name='pedidos_proveed_3d4d12_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['repartidor', '-creado_en'], name='pedidos_reparti_9480fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='pedidos_numero__a496f6_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'producto'], name='pedidos_ite_pedido__1c022d_idx'),
        ),
    ]
