# Generated by Django 5.1.7 on 2025-12-08 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_itempedido_pedido'),
        ('productos', '0006_alter_itemcarrito_precio_unitario_and_more'),
        ('proveedores', '0002_accionadministrativa_calificacion_promedio_and_more'),
        ('repartidores', '0001_initial'),
        ('usuarios', '0002_direccionfavorita_calle_secundaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricasPedido',
        ),
        migrations.AlterModelOptions(
            name='historialpedido',
            options={'ordering': ['-fecha_cambio']},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveIndex(
            model_name='itempedido',
            name='pedidos_ite_pedido__1c022d_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_proveed_3d4d12_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_reparti_9480fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_numero__a496f6_idx',
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_anterior',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_nuevo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='fecha_cambio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas (ej. sin cebolla)'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='aceptado_por_repartidor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cancelado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuarios.perfil', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comision_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comision_repartidor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='confirmado_por_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(verbose_name='Dir. Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_origen',
            field=models.TextField(blank=True, null=True, verbose_name='Dir. Origen'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_en_preparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_en_ruta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ganancia_app',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='imagen_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/evidencias/%Y/%m/', verbose_name='Evidencia Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='latitud_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='latitud_origen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='longitud_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='longitud_origen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Formato: JP-2024-000XXX', max_length=20, null=True, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='repartidores.repartidor', verbose_name='Repartidor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('proveedor', 'Pedido de Proveedor'), ('directo', 'Encargo Directo')], default='proveedor', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
