# Generated by Django 5.1.7 on 2025-12-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_delete_metricaspedido_alter_historialpedido_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_confirmado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_en_preparacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_en_ruta',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_asignado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Asignado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_en_camino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha En Camino'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_en_proceso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha En Proceso'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='instrucciones_entrega',
            field=models.TextField(blank=True, verbose_name='Instrucciones de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='confirmado_por_proveedor',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_repartidor', 'Pendiente de Repartidor'), ('asignado_repartidor', 'Asignado a Repartidor'), ('en_proceso', 'En Proceso (Recogiendo)'), ('en_camino', 'En Camino (Entrega)'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente_repartidor', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cancelado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entregado'),
        ),
    ]
