# Generated by Django 5.1.7 on 2025-12-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_fecha_confirmado_and_more'),
        ('proveedores', '0002_accionadministrativa_calificacion_promedio_and_more'),
        ('repartidores', '0002_repartidor_banco_cedula_titular_and_more'),
        ('usuarios', '0002_direccionfavorita_calle_secundaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_grupo',
            field=models.CharField(blank=True, db_index=True, help_text='UUID compartido por pedidos del mismo checkout multi-proveedor', max_length=50, null=True, verbose_name='Grupo de Pedido'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['pedido_grupo', '-creado_en'], name='pedidos_pedido__f7f4f0_idx'),
        ),
    ]
