# Generated by Django 5.1.7 on 2025-12-14 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_pedido_pedido_grupo'),
        ('proveedores', '0002_accionadministrativa_calificacion_promedio_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS pedidos_pedido__f7f4f0_idx;",
            reverse_sql=(
                "CREATE INDEX pedidos_pedido__f7f4f0_idx "
                "ON pedidos_pedido (pedido_grupo, creado_en DESC);"
            ),
            state_operations=[
                migrations.RemoveIndex(
                    model_name='pedido',
                    name='pedidos_pedido__f7f4f0_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_repartidor', 'Pendiente de Repartidor'), ('aceptado_repartidor', 'Aceptado por Repartidor'), ('asignado_repartidor', 'Asignado a Repartidor'), ('en_proceso', 'En Proceso (Recogiendo)'), ('en_camino', 'En Camino (Entrega)'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente_repartidor', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor específico (null para pedidos multi-proveedor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
