# Generated by Django 5.1.7 on 2025-12-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distancia (KM)')),
                ('tiempo_estimado_mins', models.IntegerField(default=0, verbose_name='Tiempo Estimado (min)')),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Base')),
                ('costo_km_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo KM Extra')),
                ('recargo_nocturno', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recargo Nocturno')),
                ('total_envio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Envío')),
                ('en_camino', models.BooleanField(default=False)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('lat_origen_calc', models.FloatField(null=True)),
                ('lng_origen_calc', models.FloatField(null=True)),
                ('lat_destino_calc', models.FloatField(null=True)),
                ('lng_destino_calc', models.FloatField(null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_envio', to='pedidos.pedido', verbose_name='Pedido Asociado')),
            ],
            options={
                'verbose_name': 'Envío / Logística',
                'verbose_name_plural': 'Envíos',
            },
        ),
    ]
