# Generated by Django 5.1.7 on 2025-12-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='ciudad_origen',
            field=models.CharField(blank=True, help_text='Ciudad desde donde se realiza el envío (Baños, Tena, etc.)', max_length=50, null=True, verbose_name='Ciudad de Origen'),
        ),
        migrations.AddField(
            model_name='envio',
            name='zona_destino',
            field=models.CharField(blank=True, choices=[('centro', 'Centro (Urbano)'), ('periferica', 'Periferia Cercana'), ('rural', 'Fuera de Ciudad / Rural')], help_text='Zona tarifaria calculada automáticamente', max_length=20, null=True, verbose_name='Zona de Destino'),
        ),
    ]
