# Generated by Django 5.1.7 on 2025-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_envios_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='comision_app',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión App'),
        ),
        migrations.AddField(
            model_name='envio',
            name='ganancia_conductor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganancia Conductor'),
        ),
        migrations.AddField(
            model_name='envio',
            name='lat_origen_real',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Origen (Courier)'),
        ),
        migrations.AddField(
            model_name='envio',
            name='lng_origen_real',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Origen (Courier)'),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo_servicio',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('courier', 'Courier')], default='delivery', max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
