# Generated by Django 5.1.7 on 2025-11-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
