# Generated by Django 5.1.7 on 2025-11-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_delete_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la categoría (PNG, JPG)', null=True, upload_to='categorias/', verbose_name='Imagen'),
        ),
    ]
