# Generated by Django 5.1.7 on 2025-11-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='color',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='orden',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(help_text='Imagen de la categoría (se muestra como icono circular)', upload_to='categorias/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
