# Generated by Django 5.1.7 on 2025-11-28 19:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_categoria_options_remove_categoria_color_and_more'),
        ('proveedores', '0002_accionadministrativa_calificacion_promedio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Banner Promocional', 'verbose_name_plural': 'Banners Promocionales'},
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_destaca_8cab47_idx',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se llena, el sistema calculará y mostrará el % de descuento.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Anterior (Tachado)'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='categoria_asociada',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona, al hacer click llevará a esta categoría.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='producto_asociado',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona, al hacer click llevará a este producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría (Ej: Pizza, Bebidas)', max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.carrito'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/', verbose_name='Imagen (Archivo)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Actual (Final)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rating_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiene_stock',
            field=models.BooleanField(default=False, verbose_name='Controlar Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='total_resenas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='veces_vendido',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='color',
            field=models.CharField(default='#E91E63', help_text='Color Hex del fondo (Ej: #E91E63)', max_length=7),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(help_text='Ej: Pide tus combos favoritos...'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.CharField(help_text="Ej: '20% OFF' o 'Exclusivo'", max_length=50, verbose_name='Texto Sticker'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(help_text='Ej: Combos \\$4.99', max_length=200),
        ),
    ]
