# Generated by Django 5.1.7 on 2025-12-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_carrito_options_alter_itemcarrito_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(help_text='Ej: Combos $4.99', max_length=200),
        ),
    ]
