# Generated by Django 5.1.7 on 2025-12-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_itemcarrito_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa si no se sube archivo', null=True, verbose_name='URL Imagen'),
        ),
    ]
