# Generated by Django 5.1.7 on 2025-12-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_categoria_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='productos_relacionados',
            field=models.ManyToManyField(blank=True, help_text='Productos que se sugieren junto con este', related_name='relacionado_con', to='productos.producto', verbose_name='Productos Relacionados'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo_promocion',
            field=models.CharField(choices=[('porcentaje', 'Descuento Porcentual'), ('precio_fijo', 'Precio Fijo'), ('2x1', '2x1'), ('3x2', '3x2'), ('combo', 'Combo Especial'), ('envio_gratis', 'Envío Gratis'), ('otro', 'Otro')], default='porcentaje', max_length=20, verbose_name='Tipo de Promoción'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='valor_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para porcentaje: 20 (%), para precio fijo: monto en $', max_digits=8, null=True, verbose_name='Valor del Descuento'),
        ),
    ]
