# Generated by Django 5.1.7 on 2025-12-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_productos_relacionados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='producto_asociado',
        ),
        migrations.AddField(
            model_name='promocion',
            name='productos_asociados',
            field=models.ManyToManyField(blank=True, help_text='Productos que aparecerán en esta promoción. Puedes seleccionar varios.', related_name='promociones', to='productos.producto', verbose_name='Productos Asociados'),
        ),
    ]
