# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('promocion', 'Promoción'), ('sistema', 'Sistema'), ('repartidor', 'Repartidor')], default='pedido', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=100, verbose_name='Título')),
                ('mensaje', models.TextField(help_text='Contenido de la notificación', verbose_name='Mensaje')),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Información extra en formato JSON', verbose_name='Datos adicionales')),
                ('leida', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('enviada_push', models.BooleanField(default=False, help_text='Indica si se envió notificación push', verbose_name='Enviada por push')),
                ('error_envio', models.TextField(blank=True, help_text='Mensaje de error si falló el envío push', null=True, verbose_name='Error de envío')),
                ('creada_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
