# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='pedido',
            field=models.ForeignKey(blank=True, help_text='Pedido asociado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='pedidos.pedido', verbose_name='Pedido relacionado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', '-creada_en'], name='notificacio_usuario_65ada8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_ef49b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', '-creada_en'], name='notificacio_tipo_583a01_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['pedido'], name='notificacio_pedido__aab01b_idx'),
        ),
    ]
