# Generated by Django 5.1.7 on 2025-12-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
        ('pedidos', '0004_delete_metricaspedido_alter_historialpedido_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notificacio_tipo_583a01_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notificacio_pedido__aab01b_idx',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='enviada_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='error_envio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('sistema', 'Sistema'), ('promocion', 'Promoción'), ('repartidor', 'Repartidor'), ('pago', 'Pago')], default='sistema', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
