# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.core.validators
import django.db.models.deletion
import usuarios.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_actual', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación de Usuario',
                'db_table': 'ubicaciones_usuario',
            },
        ),
        migrations.CreateModel(
            name='DireccionFavorita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('trabajo', 'Trabajo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('etiqueta', models.CharField(blank=True, max_length=50)),
                ('direccion', models.TextField(verbose_name='Dirección completa')),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('es_predeterminada', models.BooleanField(db_index=True, default=False)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('veces_usada', models.IntegerField(default=0)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección Favorita',
                'db_table': 'direcciones_favoritas',
                'ordering': ['-es_predeterminada', '-ultimo_uso'],
                'unique_together': {('user', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('alias', models.CharField(max_length=50)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), usuarios.models.validar_tamano_imagen])),
                ('observaciones', models.CharField(blank=True, max_length=100)),
                ('es_predeterminado', models.BooleanField(db_index=True, default=False)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'db_table': 'metodos_pago',
                'ordering': ['-es_predeterminado', '-created_at'],
                'unique_together': {('user', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), usuarios.models.validar_tamano_imagen], verbose_name='Foto de perfil')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fcm_token', models.CharField(blank=True, db_index=True, help_text='Token para notificaciones push', max_length=255, null=True, verbose_name='Token FCM')),
                ('fcm_token_actualizado', models.DateTimeField(blank=True, null=True, verbose_name='Ultima actualizacion token')),
                ('calificacion', models.FloatField(db_index=True, default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Calificacion promedio')),
                ('total_resenas', models.IntegerField(default=0, verbose_name='Total de resenas')),
                ('total_pedidos', models.IntegerField(default=0, verbose_name='Total pedidos')),
                ('pedidos_mes_actual', models.IntegerField(db_index=True, default=0, verbose_name='Pedidos mes actual')),
                ('ultima_actualizacion_mes', models.DateField(auto_now_add=True, verbose_name='Ultima actualizacion mes')),
                ('participa_en_sorteos', models.BooleanField(default=True, verbose_name='Participa en sorteos')),
                ('notificaciones_pedido', models.BooleanField(default=True, verbose_name='Notificaciones de pedido')),
                ('notificaciones_promociones', models.BooleanField(default=True, verbose_name='Notificaciones de promociones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'perfiles_usuario',
                'indexes': [models.Index(fields=['user', 'participa_en_sorteos'], name='perfiles_us_user_id_32b23b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioRol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_solicitado', models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('REPARTIDOR', 'Repartidor')], max_length=20)),
                ('motivo', models.TextField(max_length=500)),
                ('rol_anterior', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('REVERTIDA', 'Revertida')], db_index=True, default='PENDIENTE', max_length=20)),
                ('motivo_respuesta', models.TextField(blank=True)),
                ('revertido_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_reversion', models.TextField(blank=True)),
                ('ruc', models.CharField(blank=True, db_index=True, max_length=13, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('tipo_negocio', models.CharField(blank=True, max_length=50)),
                ('descripcion_negocio', models.TextField(blank=True)),
                ('horario_apertura', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('cedula_identidad', models.CharField(blank=True, max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50)),
                ('zona_cobertura', models.CharField(blank=True, max_length=200)),
                ('disponibilidad', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('admin_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL)),
                ('revertido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revertidas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Cambio Rol',
                'verbose_name_plural': 'Solicitudes Cambio Rol',
                'db_table': 'solicitudes_cambio_rol',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('user', 'rol_solicitado'), name='unique_pending_request')],
            },
        ),
    ]
