# Generated by Django 5.1.7 on 2025-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionfavorita',
            name='calle_secundaria',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='direccionfavorita',
            name='indicaciones',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='direccionfavorita',
            name='piso_apartamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='direccionfavorita',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
