# Generated by Django 5.1.7 on 2025-12-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccionfavorita_calle_secundaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección del negocio'),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambiorol',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
