# Generated by Django 5.1.7 on 2025-12-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitudcambiorol_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambiorol',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcambiorol',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
