# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administradores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='accionadministrativa',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='administradores.administrador', verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administradores.administrador', verbose_name='Modificado Por'),
        ),
        migrations.AddIndex(
            model_name='administrador',
            index=models.Index(fields=['activo'], name='administrad_activo_299c89_idx'),
        ),
        migrations.AddIndex(
            model_name='administrador',
            index=models.Index(fields=['-creado_en'], name='administrad_creado__64b426_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['administrador', '-fecha_accion'], name='acciones_ad_adminis_ed8395_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['tipo_accion', '-fecha_accion'], name='acciones_ad_tipo_ac_b91acf_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['modelo_afectado', 'objeto_id'], name='acciones_ad_modelo__e7a520_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['-fecha_accion'], name='acciones_ad_fecha_a_df658f_idx'),
        ),
        migrations.AddIndex(
            model_name='accionadministrativa',
            index=models.Index(fields=['exitosa', '-fecha_accion'], name='acciones_ad_exitosa_ad64a2_idx'),
        ),
    ]
