# Generated by Django 5.1.7 on 2025-12-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administradores.administrador', verbose_name='Modificado Por'),
        ),
    ]
