// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeI15CDUckBDfTiYF8eBaX1WfIQYGc6gY',
    appId: '1:78064502855:web:6e0f64d1719b57bbfdc962',
    messagingSenderId: '78064502855',
    projectId: 'delivery-109f4',
    authDomain: 'delivery-109f4.firebaseapp.com',
    storageBucket: 'delivery-109f4.firebasestorage.app',
    measurementId: 'G-QRX4DL8EZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADpzvGcnDp_mcBMcWgztm9Lx0EgywxZwk',
    appId: '1:78064502855:android:9dee11b7b638e7cafdc962',
    messagingSenderId: '78064502855',
    projectId: 'delivery-109f4',
    storageBucket: 'delivery-109f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWoM4EhXMHdlcJa4M2wQ14-1k0ji3RRNs',
    appId: '1:78064502855:ios:0d4d14bffdd38e20fdc962',
    messagingSenderId: '78064502855',
    projectId: 'delivery-109f4',
    storageBucket: 'delivery-109f4.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWoM4EhXMHdlcJa4M2wQ14-1k0ji3RRNs',
    appId: '1:78064502855:ios:0d4d14bffdd38e20fdc962',
    messagingSenderId: '78064502855',
    projectId: 'delivery-109f4',
    storageBucket: 'delivery-109f4.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeI15CDUckBDfTiYF8eBaX1WfIQYGc6gY',
    appId: '1:78064502855:web:58b3f7f26ee58d49fdc962',
    messagingSenderId: '78064502855',
    projectId: 'delivery-109f4',
    authDomain: 'delivery-109f4.firebaseapp.com',
    storageBucket: 'delivery-109f4.firebasestorage.app',
    measurementId: 'G-ZMCZ1CFVQ3',
  );
}
