# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_pagos', models.IntegerField(default=0, verbose_name='Total de Pagos')),
                ('pagos_completados', models.IntegerField(default=0, verbose_name='Pagos Completados')),
                ('pagos_pendientes', models.IntegerField(default=0, verbose_name='Pagos Pendientes')),
                ('pagos_fallidos', models.IntegerField(default=0, verbose_name='Pagos Fallidos')),
                ('pagos_reembolsados', models.IntegerField(default=0, verbose_name='Pagos Reembolsados')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Total')),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Efectivo')),
                ('monto_transferencias', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Transferencias')),
                ('monto_tarjetas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Tarjetas')),
                ('monto_reembolsado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Reembolsado')),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ticket Promedio')),
                ('tasa_exito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de pagos exitosos', max_digits=5, verbose_name='Tasa de Éxito (%)')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Estadística de Pagos',
                'verbose_name_plural': 'Estadísticas de Pagos',
                'db_table': 'pagos_estadisticas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito')], help_text='Tipo de método de pago', max_length=20, unique=True, verbose_name='Tipo')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del método', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del método de pago', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='¿El método está habilitado?', verbose_name='Activo')),
                ('requiere_verificacion', models.BooleanField(default=False, help_text='¿Requiere verificación manual? (ej: transferencias)', verbose_name='Requiere Verificación')),
                ('permite_reembolso', models.BooleanField(default=True, help_text='¿Se pueden hacer reembolsos con este método?', verbose_name='Permite Reembolso')),
                ('pasarela_nombre', models.CharField(blank=True, help_text='Nombre de la pasarela externa (Stripe, Kushki, etc.)', max_length=50, verbose_name='Nombre de Pasarela')),
                ('pasarela_api_key', models.CharField(blank=True, help_text='Clave API de la pasarela (encriptada)', max_length=255, verbose_name='API Key')),
                ('pasarela_configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración adicional en JSON', verbose_name='Configuración Pasarela')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'pagos_metodo_pago',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('reembolso', 'Reembolso'), ('ajuste', 'Ajuste'), ('propina', 'Propina')], help_text='Tipo de transacción', max_length=20, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('exitosa', models.BooleanField(blank=True, help_text='Si fue exitosa (null = en proceso)', null=True, verbose_name='Exitosa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('codigo_respuesta', models.CharField(blank=True, help_text='Código de respuesta de la pasarela', max_length=50, verbose_name='Código de Respuesta')),
                ('mensaje_respuesta', models.TextField(blank=True, help_text='Mensaje detallado de la pasarela', verbose_name='Mensaje de Respuesta')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional de la transacción', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la transacción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/dispositivo', verbose_name='User Agent')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'pagos_transacciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único del pago', unique=True, verbose_name='Referencia')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total del pago', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('monto_reembolsado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto que ha sido reembolsado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Reembolsado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', help_text='Estado actual del pago', max_length=20, verbose_name='Estado')),
                ('tarjeta_ultimos_digitos', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('tarjeta_marca', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20, verbose_name='Marca de Tarjeta')),
                ('transferencia_comprobante', models.FileField(blank=True, help_text='Comprobante de transferencia bancaria', null=True, upload_to='pagos/comprobantes/%Y/%m/', verbose_name='Comprobante')),
                ('transferencia_numero_operacion', models.CharField(blank=True, help_text='Número de operación de la transferencia', max_length=50, verbose_name='Número de Operación')),
                ('transferencia_banco', models.CharField(blank=True, help_text='Banco desde donde se realizó la transferencia', max_length=100, verbose_name='Banco Origen')),
                ('pasarela_id_transaccion', models.CharField(blank=True, db_index=True, help_text='ID de transacción de la pasarela externa', max_length=255, verbose_name='ID Transacción Pasarela')),
                ('pasarela_respuesta', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de la pasarela en JSON', verbose_name='Respuesta Pasarela')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en JSON', verbose_name='Metadata')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre el pago', verbose_name='Notas')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Fecha en que se completó el pago', null=True, verbose_name='Fecha de Completado')),
                ('fecha_reembolso', models.DateTimeField(blank=True, help_text='Fecha del último reembolso', null=True, verbose_name='Fecha de Reembolso')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.metodopago', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
