# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(help_text='Pedido asociado al pago', on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='pago',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario admin que verificó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pagos.pago', verbose_name='Pago'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['-creado_en'], name='pagos_creado__834757_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='pagos_estado_79b102_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='pagos_metodo__bde486_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['referencia'], name='pagos_referen_20116e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['pasarela_id_transaccion'], name='pagos_pasarel_09c0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado', 'creado_en'], name='pagos_estado_13ddbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_reembolsado__lte', models.F('monto'))), name='pago_reembolso_valido'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['pago', '-creado_en'], name='pagos_trans_pago_id_c2d35b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo'], name='pagos_trans_tipo_0815c6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['exitosa'], name='pagos_trans_exitosa_8e2552_idx'),
        ),
    ]
