# Generated by Django 5.1.7 on 2025-11-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='transferencia_banco_origen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco Origen (Cliente)'),
        ),
    ]
