# Generated by Django 5.1.7 on 2025-11-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_add_transferencia_banco_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='transferencia_banco',
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
                default='',
                help_text='Banco desde donde se realizó la transferencia',
                verbose_name='Banco Origen'
            ),
        ),
    ]
