# Generated by Django 5.1.7 on 2025-12-01 19:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_alter_transferencia_banco_nullable'),
        ('pedidos', '0003_alter_itempedido_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticaspago',
            options={'verbose_name': 'Estadística Diaria', 'verbose_name_plural': 'Estadísticas Diarias'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RemoveConstraint(
            model_name='pago',
            name='pago_monto_positivo',
        ),
        migrations.RemoveConstraint(
            model_name='pago',
            name='pago_reembolso_valido',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_creado__834757_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_estado_79b102_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_metodo__bde486_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_referen_20116e_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_pasarel_09c0c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pagos_estado_13ddbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaccion',
            name='pagos_trans_pago_id_c2d35b_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaccion',
            name='pagos_trans_tipo_0815c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaccion',
            name='pagos_trans_exitosa_8e2552_idx',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='transferencia_banco',
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='fecha',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='monto_reembolsado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='monto_tarjetas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='monto_transferencias',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='pagos_completados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='pagos_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='pagos_pendientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='pagos_reembolsados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='tasa_exito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='ticket_promedio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='estadisticaspago',
            name='total_pagos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='pasarela_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='pasarela_configuracion',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración Pasarela'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='pasarela_nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre de Pasarela'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='permite_reembolso',
            field=models.BooleanField(default=True, verbose_name='Permite Reembolso'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='requiere_verificacion',
            field=models.BooleanField(default=False, help_text='Si es True, el pago no se completa automáticamente (ej. Transferencia)', verbose_name='Requiere Verificación'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito')], max_length=20, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('esperando_verificacion', 'Esperando Verificación (Chofer/Admin)'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_reembolso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_reembolsado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Reembolsado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas de Auditoría'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pasarela_id_transaccion',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pasarela_respuesta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tarjeta_marca',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tarjeta_ultimos_digitos',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='pago',
            name='transferencia_comprobante',
            field=models.ImageField(blank=True, help_text='Foto del comprobante subida por el cliente', null=True, upload_to='pagos/comprobantes/%Y/%m/', verbose_name='Comprobante (Foto)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='transferencia_numero_operacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Num. Operación'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario (Chofer o Admin) que confirmó la recepción del dinero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='codigo_respuesta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='exitosa',
            field=models.BooleanField(blank=True, help_text='True=Exitosa, False=Fallida, Null=En Proceso', null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='mensaje_respuesta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pagos.pago'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('pago', 'Pago'), ('reembolso', 'Reembolso'), ('ajuste', 'Ajuste'), ('propina', 'Propina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
