# Generated by Django 5.1.7 on 2025-12-12 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_estadisticaspago_options_and_more'),
        ('repartidores', '0002_repartidor_banco_cedula_titular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_visible_repartidor',
            field=models.BooleanField(default=False, help_text='Indica si el comprobante está disponible para que el repartidor lo vea', verbose_name='Comprobante Visible para Repartidor'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_visualizacion_repartidor',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el repartidor vio el comprobante', null=True, verbose_name='Fecha Visualización Repartidor'),
        ),
        migrations.AddField(
            model_name='pago',
            name='repartidor_asignado',
            field=models.ForeignKey(blank=True, help_text='Repartidor que debe verificar el comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_asignados', to='repartidores.repartidor', verbose_name='Repartidor Asignado'),
        ),
    ]
