# Generated by Django 5.1.7 on 2025-11-25 03:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='repartidores/perfil/')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('fuera_servicio', 'Fuera de Servicio')], default='fuera_servicio', max_length=20)),
                ('verificado', models.BooleanField(default=False, help_text='Aprobado por un administrador.')),
                ('activo', models.BooleanField(default=True, help_text='Soft-disable sin borrar datos.')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('ultima_localizacion', models.DateTimeField(blank=True, null=True)),
                ('entregas_completadas', models.PositiveIntegerField(default=0)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repartidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'db_table': 'repartidores',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ubicaciones', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'Historial de Ubicación',
                'verbose_name_plural': 'Historial de Ubicaciones',
                'db_table': 'repartidores_historial_ubicacion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pedido_id', models.CharField(max_length=100)),
                ('puntuacion', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_a_repartidores', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'Calificación a Repartidor',
                'verbose_name_plural': 'Calificaciones a Repartidores',
                'db_table': 'repartidores_calificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pedido_id', models.CharField(max_length=100)),
                ('puntuacion', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_de_repartidores', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_a_clientes', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'Calificación a Cliente',
                'verbose_name_plural': 'Calificaciones a Clientes',
                'db_table': 'clientes_calificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RepartidorEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('fuera_servicio', 'Fuera de Servicio')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('fuera_servicio', 'Fuera de Servicio')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_estado', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'Log de Estado de Repartidor',
                'verbose_name_plural': 'Logs de Estado de Repartidor',
                'db_table': 'repartidores_estado_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RepartidorVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('motocicleta', 'Motocicleta'), ('bicicleta', 'Bicicleta'), ('automovil', 'Automóvil'), ('camioneta', 'Camioneta'), ('otro', 'Otro')], max_length=20)),
                ('placa', models.CharField(blank=True, max_length=15, null=True)),
                ('licencia_foto', models.ImageField(blank=True, null=True, upload_to='repartidores/licencias/')),
                ('activo', models.BooleanField(default=True, help_text='Debe existir solo un vehículo activo por repartidor.')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'Vehículo de Repartidor',
                'verbose_name_plural': 'Vehículos de Repartidor',
                'db_table': 'repartidores_vehiculos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='repartidor',
            index=models.Index(fields=['estado'], name='repartidore_estado_b930db_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidor',
            index=models.Index(fields=['verificado'], name='repartidore_verific_d73386_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidor',
            index=models.Index(fields=['activo'], name='repartidore_activo_601c03_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidor',
            index=models.Index(fields=['ultima_localizacion'], name='repartidore_ultima__68a972_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidor',
            index=models.Index(fields=['user'], name='repartidore_user_id_f45a55_idx'),
        ),
        migrations.AddConstraint(
            model_name='repartidor',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'fuera_servicio'), ('verificado', True), _connector='OR'), name='rep_estado_req_verificado'),
        ),
        migrations.AddConstraint(
            model_name='repartidor',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__isnull', True), models.Q(('latitud__gte', -5.0), ('latitud__lte', 2.0)), _connector='OR'), name='rep_lat_ec'),
        ),
        migrations.AddConstraint(
            model_name='repartidor',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__isnull', True), models.Q(('longitud__gte', -92.0), ('longitud__lte', -75.0)), _connector='OR'), name='rep_lon_ec'),
        ),
        migrations.AddIndex(
            model_name='historialubicacion',
            index=models.Index(fields=['repartidor', 'timestamp'], name='repartidore_reparti_ef720c_idx'),
        ),
        migrations.AddIndex(
            model_name='historialubicacion',
            index=models.Index(fields=['timestamp'], name='repartidore_timesta_fd3fce_idx'),
        ),
        migrations.AddConstraint(
            model_name='historialubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -5.0), ('latitud__lte', 2.0)), name='hist_lat_ec'),
        ),
        migrations.AddConstraint(
            model_name='historialubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -92.0), ('longitud__lte', -75.0)), name='hist_lon_ec'),
        ),
        migrations.AddIndex(
            model_name='calificacionrepartidor',
            index=models.Index(fields=['repartidor'], name='repartidore_reparti_b2b5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionrepartidor',
            index=models.Index(fields=['cliente'], name='repartidore_cliente_0874d1_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionrepartidor',
            index=models.Index(fields=['pedido_id'], name='repartidore_pedido__b755b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='calificacionrepartidor',
            constraint=models.UniqueConstraint(fields=('repartidor', 'cliente', 'pedido_id'), name='unique_calif_cliente_repartidor_por_pedido'),
        ),
        migrations.AddConstraint(
            model_name='calificacionrepartidor',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), name='calif_rep_rango'),
        ),
        migrations.AddIndex(
            model_name='calificacioncliente',
            index=models.Index(fields=['cliente'], name='clientes_ca_cliente_e6556e_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacioncliente',
            index=models.Index(fields=['repartidor'], name='clientes_ca_reparti_aee60b_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacioncliente',
            index=models.Index(fields=['pedido_id'], name='clientes_ca_pedido__01db07_idx'),
        ),
        migrations.AddConstraint(
            model_name='calificacioncliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'repartidor', 'pedido_id'), name='unique_calif_repartidor_cliente_por_pedido'),
        ),
        migrations.AddConstraint(
            model_name='calificacioncliente',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), name='calif_cli_rango'),
        ),
        migrations.AddIndex(
            model_name='repartidorestadolog',
            index=models.Index(fields=['repartidor', 'timestamp'], name='repartidore_reparti_6d5efc_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidorestadolog',
            index=models.Index(fields=['estado_nuevo'], name='repartidore_estado__2aa483_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidorvehiculo',
            index=models.Index(fields=['repartidor'], name='repartidore_reparti_ad2998_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidorvehiculo',
            index=models.Index(fields=['tipo'], name='repartidore_tipo_f739db_idx'),
        ),
        migrations.AddIndex(
            model_name='repartidorvehiculo',
            index=models.Index(fields=['activo'], name='repartidore_activo_ccfd15_idx'),
        ),
        migrations.AddConstraint(
            model_name='repartidorvehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('placa__isnull', False)), fields=('repartidor', 'placa'), name='unique_placa_por_repartidor'),
        ),
    ]
