# Generated by Django 5.1.7 on 2025-12-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='banco_cedula_titular',
            field=models.CharField(blank=True, help_text='Cédula del titular de la cuenta', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='banco_fecha_verificacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de verificación bancaria', null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='banco_nombre',
            field=models.CharField(blank=True, help_text='Nombre del banco', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='banco_numero_cuenta',
            field=models.CharField(blank=True, help_text='Número de cuenta bancaria', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='banco_tipo_cuenta',
            field=models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], help_text='Tipo de cuenta bancaria', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='banco_titular',
            field=models.CharField(blank=True, help_text='Nombre completo del titular', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='banco_verificado',
            field=models.BooleanField(default=False, help_text='Datos bancarios verificados por admin'),
        ),
    ]
